// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2aXgUGK8hwsUkEuGSTBdCqviJNCyrykg',
    appId: '1:832521333616:web:85ffea5ca15907c6b5bdb5',
    messagingSenderId: '832521333616',
    projectId: 'farmfusion-ee003',
    authDomain: 'farmfusion-ee003.firebaseapp.com',
    storageBucket: 'farmfusion-ee003.appspot.com',
    measurementId: 'G-PW8DV1KSFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPLoLaFfrc2wM3J0EJCCAkPrhjxWBTWGs',
    appId: '1:832521333616:android:0aaeab69827ae7c7b5bdb5',
    messagingSenderId: '832521333616',
    projectId: 'farmfusion-ee003',
    storageBucket: 'farmfusion-ee003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXO32jB4QIwMnXMCSLQ1BrFYROUS8Hp-s',
    appId: '1:832521333616:ios:e891c56aeb502eacb5bdb5',
    messagingSenderId: '832521333616',
    projectId: 'farmfusion-ee003',
    storageBucket: 'farmfusion-ee003.appspot.com',
    iosBundleId: 'com.example.farmfusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXO32jB4QIwMnXMCSLQ1BrFYROUS8Hp-s',
    appId: '1:832521333616:ios:e891c56aeb502eacb5bdb5',
    messagingSenderId: '832521333616',
    projectId: 'farmfusion-ee003',
    storageBucket: 'farmfusion-ee003.appspot.com',
    iosBundleId: 'com.example.farmfusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2aXgUGK8hwsUkEuGSTBdCqviJNCyrykg',
    appId: '1:832521333616:web:8c3c101db12eb891b5bdb5',
    messagingSenderId: '832521333616',
    projectId: 'farmfusion-ee003',
    authDomain: 'farmfusion-ee003.firebaseapp.com',
    storageBucket: 'farmfusion-ee003.appspot.com',
    measurementId: 'G-1FS82G5466',
  );
}
