// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgqrAtbzbAya9qYzIJZW0K9ov1aLMQ-6U',
    appId: '1:576895783833:web:e62bdb741434dafef33908',
    messagingSenderId: '576895783833',
    projectId: 'clgproject-b0570',
    authDomain: 'clgproject-b0570.firebaseapp.com',
    storageBucket: 'clgproject-b0570.appspot.com',
    measurementId: 'G-KM624ZN79D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJWguwu20kHPxHKGQHV9BtZq12RCeko8Q',
    appId: '1:576895783833:android:8235c500a6f3ca59f33908',
    messagingSenderId: '576895783833',
    projectId: 'clgproject-b0570',
    storageBucket: 'clgproject-b0570.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyB8FGjwBAwzYwifZy8drIv1q2zjK1Pow',
    appId: '1:576895783833:ios:a8ae9a6029b99173f33908',
    messagingSenderId: '576895783833',
    projectId: 'clgproject-b0570',
    storageBucket: 'clgproject-b0570.appspot.com',
    iosBundleId: 'com.example.farmfusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyB8FGjwBAwzYwifZy8drIv1q2zjK1Pow',
    appId: '1:576895783833:ios:a8ae9a6029b99173f33908',
    messagingSenderId: '576895783833',
    projectId: 'clgproject-b0570',
    storageBucket: 'clgproject-b0570.appspot.com',
    iosBundleId: 'com.example.farmfusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgqrAtbzbAya9qYzIJZW0K9ov1aLMQ-6U',
    appId: '1:576895783833:web:5a426b4ae8c8d59df33908',
    messagingSenderId: '576895783833',
    projectId: 'clgproject-b0570',
    authDomain: 'clgproject-b0570.firebaseapp.com',
    storageBucket: 'clgproject-b0570.appspot.com',
    measurementId: 'G-54HD8VLWWC',
  );

}